name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        mode: [DEBUG, RELEASE]
        lang: [EN, CN]

    runs-on: ubuntu-latest
    container: archlinuxrolling/base:latest

    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: |
        pacman -Syu --noconfirm --needed base-devel gcc make clang readline python python-pip
        pip install ply
    - name: "make install (Mode: ${{ matrix.mode }}) (Language: ${{ matrix.lang }})"
      run: make install ${{ matrix.mode }}=1 LANG=${{ matrix.lang }} DESTDIR=dist-${{ matrix.mode }}-${{ matrix.lang }}
    - name: Upload artifact dist-${{ matrix.mode }}-${{ matrix.lang }}
      uses: actions/upload-artifact@v1.0.0
      with:
        name: dist-${{ matrix.mode }}-${{ matrix.lang }}
        path: dist-${{ matrix.mode }}-${{ matrix.lang }}